const fs = require('fs');
const path = require('path');

const docsRoot = path.join(__dirname, '..', 'docs');
const enDir = path.join(docsRoot, 'en');
const itDir = path.join(docsRoot, 'it');

function ensureDir(d){ if(!fs.existsSync(d)) fs.mkdirSync(d,{recursive:true}); }

// Phrase dictionary: longer phrases first
const phraseMap = [
  ['The entry point of the generated kernel.', 'Il punto di ingresso del kernel generato.'],
  ['Print text using the kernel screen runtime.', 'Stampa testo usando il runtime dello schermo del kernel.'],
  ['Print a signed integer.', 'Stampa un intero con segno.'],
  ['Repeat these blocks forever.', 'Ripeti questi blocchi all\'infinito.'],
  ['Repeat while a condition is true.', 'Ripeti finché una condizione è vera.'],
  ['Run blocks only when the condition is true.', 'Esegui i blocchi solo quando la condizione è vera.'],
  ['Number of files embedded into the bootable ISO.', 'Numero di file incorporati nell\'ISO avviabile.'],
  ['Read an uploaded file name.', 'Leggi il nome di un file caricato.'],
  ['Read an uploaded file size in bytes.', 'Leggi la dimensione in byte di un file caricato.'],
  ['A 24-bit RGB colour value.', 'Un valore colore RGB a 24 bit.'],
  ['True after the Run input box sends a complete line ending in Enter.', 'Vero dopo che la casella di input Run invia una riga completa terminata da Invio.']
];

const wordMap = {
  'block':'blocco','blocks':'blocchi','Repeat':'Ripeti','repeat':'ripeti','If':'Se','if':'se','else':'altrimenti',
  'and':'e','or':'o','true':'vero','false':'falso','String':'Stringa','Number':'Numero'
};

function translateText(s){
  if(!s) return s;
  let out = s;
  // phrases
  phraseMap.forEach(([eng,it])=>{ out = out.split(eng).join(it); });
  // words
  Object.keys(wordMap).forEach(k=>{
    const v = wordMap[k];
    // word boundaries
    out = out.replace(new RegExp('\\b'+k+'\\b','g'), v);
  });
  // small punctuation fixes
  out = out.replace(/\bC\b/g,'C');
  // append note if appears autogenerated
  if(!out.includes('NOTE: traduzione automatica') && /NOTE: traduzione automatica/.length>0){
    out = out.replace('\n\n> NOTE: traduzione automatica, verificare','');
  }
  return out;
}

function processFile(enPath,itPath){
  const content = fs.readFileSync(enPath,'utf8');
  let res = content;
  // translate headings and simple lines
  res = res.split('\n').map(line=>{
    // preserve code fences
    if(line.trim().startsWith('```')) return line;
    // translate headings and inline text but not markdown links
    // simple heuristic: do not touch lines that start with '- [' (index links)
    if(/^\s*- \[/.test(line)) return line;
    // translate content between backticks? skip
    // apply phrase/word translation
    return translateText(line);
  }).join('\n');
  // append review note
  if(!res.includes('> NOTE: traduzione automatica')) res += '\n\n> NOTE: traduzione automatica, verificare e adattare gli esempi.';
  fs.writeFileSync(itPath, res, 'utf8');
}

function main(){
  ensureDir(itDir);
  const files = fs.readdirSync(enDir).filter(f=>f.endsWith('.md'));
  files.forEach(f=>{
    const enPath = path.join(enDir,f);
    const itPath = path.join(itDir,f);
    try{ processFile(enPath,itPath); console.log('Translated', f); }catch(e){ console.error('Failed',f,e); }
  });
  console.log('Translation pass complete.');
}

main();
